### ISSUE TITLE
crashes 4.0.295.0 unstable

### ISSUE THREAD

**Issue by joedeveloper** [endtwist/AjaxIM#4]
per title. crashes tab upon finishing loading ajaxim.com

**Comment by endtwist** [comment]
This is really vague. I need more information about the OS, browser, browser version, and any installed extensions (Firebug, etc.).

**Comment by joedeveloper** [comment]
Hah, sorry, just noticed that. 
Google Chrome 4.0.295.0 unstable on debian lenny. No extensions.

**Comment by joedeveloper** [comment]
This is also replicated on  osx/chromium by a #node.js user

**Comment by benhutchins** [comment]
I am using Google Chrome 5.0.307.9 beta in Debian and it doesn't crash. Version 4.0 has a lot of bugs in it, and all Google Chrome releases are in beta currently in Linux. I'd pass this as a bug to address after there is a stable release for linux, if it still exists then (seeing how it's fixed in 5.0 I'd assume it won't exist then).

**Comment by endtwist** [comment]
Since this is occurring in beta/unstable builds, I won't fix this. If it is still an issue once stable builds come around, then I will reconsider.

For the record, it works fine in Google Chrome 5.0.322.2 on OS X.

**Comment by joedeveloper** [comment]
just upgraded to 5.0.307.9 beta on debian and for some reason it is still crashing, not immediately, and I was able to chat with a random user, but it crashed after I navigated to documentation. I understand your point re unstable however.
