### ISSUE TITLE
"Can't set headers after they are sent" in Express next() function.

### ISSUE THREAD

**Issue by zkorz** [endtwist/AjaxIM#54]
In the authentication library index.js (export.friends):

 response.on('end', function() {
    try {
           callback(JSON.parse(data));
     } catch(e) {
          console.log("ERROR: "+e.message);
       callback();
      }
});

Whenever a user logs in the "try" callback is running and successfully logging them in, but then an error is thrown in the Express next() function located near the end of im.js:

...
res.signOff = function() { store.signOff(req.sessionID); };

next();
...

The e.message prints out "Can't set headers after they are sent". 

Also, when callback() is run in the catch section with no arguments there is a fatal error because "friends" is undefined and trying to be sliced in hub.js "var friends_copy = friends.slice();".

When I comment out callback() in the catch section I get signed in with no problems. An object is returned with my username and the list of friends expected from my getuser.php and getfriends.php. I am even able to sign in other users and chat successfully, but I am getting lots of other problems if users sign in and out. I figure these other random problems could be related to the error when the user logs in. 

I've been trying to get this setup for a week now and feel very close. 

Thanks for your help.

**Comment by ajaximrpg** [comment]
The "Can't set headers after they are sent" message is fixed in the latest "master" branch, in AjaxIM/server/middleware/im.js .  The "listen" URL must not be sent on to the next() handler because it is a long running page.  Once it starts running, all future accesses can add to the body only; if an attempt to change the header is made, even with an unneeded change, an error is emitted.

Please reopen or post a new issue if the latest code doesn't work for you.
